/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PurchaseRouteImport } from './routes/purchase'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as AuthSingUpRouteImport } from './routes/_auth/sing-up'
import { Route as AuthSingInRouteImport } from './routes/_auth/sing-in'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRoute = PurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSingUpRoute = AuthSingUpRouteImport.update({
  id: '/sing-up',
  path: '/sing-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSingInRoute = AuthSingInRouteImport.update({
  id: '/sing-in',
  path: '/sing-in',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/purchase': typeof PurchaseRoute
  '/search': typeof SearchRoute
  '/sing-in': typeof AuthSingInRoute
  '/sing-up': typeof AuthSingUpRoute
  '/products/$id': typeof ProductsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/purchase': typeof PurchaseRoute
  '/search': typeof SearchRoute
  '/sing-in': typeof AuthSingInRoute
  '/sing-up': typeof AuthSingUpRoute
  '/products/$id': typeof ProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/purchase': typeof PurchaseRoute
  '/search': typeof SearchRoute
  '/_auth/sing-in': typeof AuthSingInRoute
  '/_auth/sing-up': typeof AuthSingUpRoute
  '/products/$id': typeof ProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/purchase'
    | '/search'
    | '/sing-in'
    | '/sing-up'
    | '/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/purchase' | '/search' | '/sing-in' | '/sing-up' | '/products/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/purchase'
    | '/search'
    | '/_auth/sing-in'
    | '/_auth/sing-up'
    | '/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PurchaseRoute: typeof PurchaseRoute
  SearchRoute: typeof SearchRoute
  ProductsIdRoute: typeof ProductsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase': {
      id: '/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sing-up': {
      id: '/_auth/sing-up'
      path: '/sing-up'
      fullPath: '/sing-up'
      preLoaderRoute: typeof AuthSingUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sing-in': {
      id: '/_auth/sing-in'
      path: '/sing-in'
      fullPath: '/sing-in'
      preLoaderRoute: typeof AuthSingInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSingInRoute: typeof AuthSingInRoute
  AuthSingUpRoute: typeof AuthSingUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSingInRoute: AuthSingInRoute,
  AuthSingUpRoute: AuthSingUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PurchaseRoute: PurchaseRoute,
  SearchRoute: SearchRoute,
  ProductsIdRoute: ProductsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
